packages:
  - examples/*
overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
onlyBuiltDependencies:
  - esbuild
